### ISSUE TITLE
Getting this error when running on a Windows build

### ISSUE THREAD

**Issue by jmartinVL** [newyellow/Unity-Runtime-Animation-Recorder#1]
at AnimationCurveUtility.SetLinear (UnityEngine.AnimationCurve& curve) [0x00038] in C:\Users\Jesus\Documents\Unity Projects\formula_E_2\formula_E\Assets\Modules\AnimationGeneration\AnimationCurveUtility.cs:38 

This is the line:
 field.SetValue(boxed, GetNewTangentKeyMode((int)field.GetValue(boxed), TangentDirection.Left, TangentMode.Linear));

**Comment by newyellow** [comment]
hmm, the error seems not come from my script. Would you explain what you were trying to do?
Or would you mind sharing the script or the project to me?

**Comment by jmartinVL** [comment]
Hi there!
Explain it is a little complex... we have a very complex car racing scene,
where cars are moving following GPS real time data from a real race, and
replicating the moving as a animation give us a better smooth movement.
I solved the problem changing the set linear function. Here you got what I
have used:

public static void SetLinear(AnimationCurve curve)
    {
        for (int i = 0; i < curve.keys.Length; ++i)
        {
            float intangent = 0;
            float outtangent = 0;
            bool intangent_set = false;
            bool outtangent_set = false;
            Vector2 point1;
            Vector2 point2;
            Vector2 deltapoint;
            Keyframe key = curve[i];

```
        if (i == 0)
        {
            intangent = 0; intangent_set = true;
        }

        if (i == curve.keys.Length - 1)
        {
            outtangent = 0; outtangent_set = true;
        }

        if (!intangent_set)
        {
            point1.x = curve.keys[i - 1].time;
            point1.y = curve.keys[i - 1].value;
            point2.x = curve.keys[i].time;
            point2.y = curve.keys[i].value;

            deltapoint = point2 - point1;

            intangent = deltapoint.y / deltapoint.x;
        }
        if (!outtangent_set)
        {
            point1.x = curve.keys[i].time;
            point1.y = curve.keys[i].value;
            point2.x = curve.keys[i + 1].time;
            point2.y = curve.keys[i + 1].value;

            deltapoint = point2 - point1;

            outtangent = deltapoint.y / deltapoint.x;
        }

        key.inTangent = intangent;
        key.outTangent = outtangent;
        curve.MoveKey(i, key);
    }
}
```

Anyway thank you very much, your script have helped me to understand how to
build animations by code.

**Comment by newyellow** [comment]
You're welcome, you solved it yourself, I helped nothing haha.
