### ISSUE TITLE
Unity Animation recorder not working...

### ISSUE THREAD

**Issue by howardt12345** [newyellow/Unity-Runtime-Animation-Recorder#3]
It appears as if the animation recorder is not working. I'm on Unity 5.4.1f1 and whenever I try to record an animation, the animation clip would only have 2 curves and wouldn't have that I actually recorded... 
![image](https://cloud.githubusercontent.com/assets/16857036/18833624/9850ddfe-83bf-11e6-9c15-a4285567dadf.png)
I have this spectrum that reacts to audio, and what I used to do in Unity 5.4.0 was that I would record it and the Animation recorder would return a relatively large file that would usually have these settings:
![image](https://cloud.githubusercontent.com/assets/16857036/18833671/dfe6af9a-83bf-11e6-8d54-3c564602a383.png)
Now,  this is what I'm getting from the animation recorder:
![image](https://cloud.githubusercontent.com/assets/16857036/18833688/f5def672-83bf-11e6-8c06-a9c5f8368c55.png)
There's also no errors or warnings in the console, so I have no idea what's happening...

Edit:
For the sake of experimentation, I put 50 spheres as a child to a gameObject with only the Animation recorder on it and recorded the falling from the rigibody component. I then took the rigibody out and put the animation clip on the parent object. It seemed to work...

Edit 2:
I even recorded the falling of 100 spheres and even that seemed to work...

Edit 3: 
I found out that the cubes aren't recording because they all have the exact same name... I'll close this issue, sorry about that haha

**Comment by newyellow** [comment]
haha yeah! That's how unity .anim files work. They animate object by name. GameObject name matters!

**Comment by howardt12345** [comment]
Now I know xD
