### ISSUE TITLE
Issue recording mutliple animations

### ISSUE THREAD

**Issue by spaggi2** [newyellow/Unity-Runtime-Animation-Recorder#5]
If I record one animation by pressing "Start" and "Stop" it works great.

When recording more animations, e.g. by pressing "Start", "Stop", "Start", "Stop" and changing the filename inbetween the second animation will consist of the first and the second one. I this expected behavior?

**Comment by spaggi2** [comment]
Just so you know, I achieved the desired result of restarting animation recording from scratch by removing and re-adding your component at runtime. So I'm happy! Again, thank you so much for this!

**Comment by newyellow** [comment]
Didn't expect this kind of behavior before haha.

I made a small update, which makes you can stop/start recording multiple times in one run, and the script will rename the file for you, then you don't have to edit the filename.

And if you use the changeTimeScale feature, timescale will change when you stop recording.

try it though!
