### ISSUE TITLE
If recordLimitedFrames is false it only records the default (1000 frames)

### ISSUE THREAD

**Issue by cpaganucci** [newyellow/Unity-Runtime-Animation-Recorder#9]
I would expect it to continue recording until I hit the stop key.

If I change UnityAnimationRecorder.cs line 103 from:

if (frameIndex < recordFrames) {

to:

if ( recordLimitedFrames && frameIndex >= recordFrames) {

and swap the code in the if/else statement, then it will continue to record until I stop it manually.

**Comment by newyellow** [comment]
Haha, this is really a silly error. Gonna fix it!
